### ISSUE TITLE
Mac编译安装后执行HikyuuTDX报错

### ISSUE THREAD

**Issue by wjlxyz** [fasiondog/hikyuu#68]
$ HikyuuTDX
Traceback (most recent call last):
  File "/usr/local/bin/HikyuuTDX", line 5, in <module>
    from hikyuu.gui.HikyuuTDX import start
  File "/usr/local/lib/python3.9/site-packages/hikyuu/__init__.py", line 51, in <module>
    from .util import *
  File "/usr/local/lib/python3.9/site-packages/hikyuu/util/__init__.py", line 51, in <module>
    from .util import *
ModuleNotFoundError: No module named 'hikyuu.util.util'
(base)

**Comment by fasiondog** [comment]
macosx已优化支持
