### ISSUE TITLE
哪个linuxDocker安装后在python中运行也出错误提示.

### ISSUE THREAD

**Issue by zhangshoug** [fasiondog/hikyuu#8]
root@d427a9d9d289:~# python
Python 3.6.5 |Anaconda custom (64-bit)| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from hikyuu.interactive.interactive import * 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fasiondog/hikyuu/tools/hikyuu/__init__.py", line 56, in <module>
    from .core import *
  File "/home/fasiondog/hikyuu/tools/hikyuu/core.py", line 34, in <module>
    from .core_doc import *
  File "/home/fasiondog/hikyuu/tools/hikyuu/core_doc.py", line 28, in <module>
    from hikyuu._hikyuu import *
ImportError: libhikyuu.so: cannot open shared object file: No such file or directory
>>> exit
Use exit() or Ctrl-D (i.e. EOF) to exit
>>> 
root@d427a9d9d289:~# find ./ -name libhikyuu.so
./hikyuu/build/hikyuu/gcc-5.4.0/release/libhikyuu.so
./hikyuu/tools/hikyuu/libhikyuu.so
root@d427a9d9d289:~#

**Comment by zhangshoug** [comment]
又重新安装了一遍Docker,这次出来下面提示:
root@c8dad2556de1:~# python
Python 3.6.5 |Anaconda custom (64-bit)| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from hikyuu.interactive.interactive import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'hikyuu.interactive'

**Comment by zhangshoug** [comment]
在家中Linux机器上Docker安装和非Docker出现如下提示:
root@1d5ef042c91f:~# python
Python 3.6.5 |Anaconda custom (64-bit)| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from hikyuu.interactive.interactive import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fasiondog/hikyuu/tools/hikyuu/__init__.py", line 56, in <module>
    from .core import *
  File "/home/fasiondog/hikyuu/tools/hikyuu/core.py", line 34, in <module>
    from .core_doc import *
  File "/home/fasiondog/hikyuu/tools/hikyuu/core_doc.py", line 28, in <module>
    from hikyuu._hikyuu import *
ImportError: /home/fasiondog/hikyuu/tools/hikyuu/libhikyuu.so: undefined symbol: mysql_num_rows
>>>

**Comment by zhangshoug** [comment]
再运行，出现
root@8d6d72eeef09:~# python
Python 2.7.15 |Anaconda custom (64-bit)| (default, May  1 2018, 23:32:55) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from hikyuu.interactive.interactive import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fasiondog/hikyuu/tools/hikyuu/__init__.py", line 56, in <module>
    from .core import *
  File "/home/fasiondog/hikyuu/tools/hikyuu/core.py", line 34, in <module>
    from .core_doc import *
  File "/home/fasiondog/hikyuu/tools/hikyuu/core_doc.py", line 28, in <module>
    from hikyuu._hikyuu import *
ImportError: /usr/local/lib/libboost_python3.so.1.64.0: undefined symbol: PyUnicode_AsUTF8String
